export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FILTERED_BRANCHS_BY_CATEGORY = 'FILTERED_BRANCHS_BY_CATEGORY';
export const LIST_OF_ORGANISATIONS = 'LIST_OF_ORGANISATIONS';
export const LIST_OF_USERS= 'LIST_OF_USERS';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
