export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LIST_OF_CATEGORIES = 'LIST_OF_CATEGORIES';
export const LIST_OF_BOROUGHS = 'LIST_OF_BOROUGHS';
export const LIST_OF_AREAS = 'LIST_OF_AREAS';
export const FILTERED_BRANCHS_BY_CATEGORY = 'FILTERED_BRANCHS_BY_CATEGORY';
export const LIST_OF_ORGANISATIONS = 'LIST_OF_ORGANISATIONS';
